// STATIC FALLBACK DATA FOR OFFLINE / FALLBACK MODE

export const STATIC_COMPANY_PROFILE = {
  company_name: "Bymer Elastomers",
  tagline: "Delivering precision-engineered elastomer solutions with uncompromising quality since 1999. IATF 16949:2016, ISO 9001:2015 and ISO 14001:2015 certified.",
  logo_url: null, // will fall back to local SVG/Image
  email: "sales@bymer.com",
  phone: "+919822079899",
  alternate_phone: "+912532381123",
  address: "Plot No. J-46 & 47 MIDC Area, Ambad, Nashik 422010, Maharashtra, India.",
  website: "https://www.bymer.com",
};

export const STATIC_SOCIAL_LINKS = [
  { id: "s-1", platform: "LinkedIn", url: "https://linkedin.com" },
  { id: "s-2", platform: "YouTube", url: "https://youtube.com" },
  { id: "s-3", platform: "Email", url: "mailto:sales@bymer.com" },
];

export const STATIC_STATISTICS = [
  { id: "st-1", label: "YEARS EXPERIENCE", value: "30+" },
  { id: "st-2", label: "GLOBAL CLIENTS", value: "50+" },
  { id: "st-3", label: "PROJECTS COMPLETED", value: "1150+" },
  { id: "st-4", label: "SATISFIED CLIENTS", value: "150+" },
];

export const STATIC_CLIENTS = [
  { id: 1, image: "/images/L14 2.png" },
  { id: 2, image: "/images/L15 2.png" },
  { id: 3, image: "/images/L16 2.png" },
  { id: 4, image: "/images/1728122557.png" },
  { id: 5, image: "/images/L18 2.png" },
  { id: 6, image: "/images/L19 2.png" },
];

export const STATIC_PRODUCT_CATEGORIES = [
  { id: 1, name: "Automotive" },
  { id: 2, name: "Non Automotive" },
];

export const STATIC_PRODUCT_CATEGORY_DETAILS = {
  1: {
    id: 1,
    name: "Automotive",
    customers: [
      { id: 11, name: "ACCURA VALVES PVT. LTD., NASHIK, INDIA" },
      { id: 4, name: "AUTO IGNITION LIMITED, SATARA, INDIA" },
      { id: 3, name: "ELRINGKLINGER AUTOMOTIVE COMPONENTS (I) PVT. LTD., PUNE, INDIA" },
      { id: 2, name: "GABRIEL INDIA LTD., NASHIK, HOSUR AND SANAND" },
      { id: 1, name: "HORDAGRUPPEN AB, SWEDEN" },
      { id: 8, name: "LILJAS PLASTIC SUZHOU CO., LTD., CHINA" },
      { id: 5, name: "PIAGGIO VEHICLES PVT. LTD., BARAMATI, INDIA" },
      { id: 6, name: "POONA SHIMS PRIVATE LIMITED, PUNE, INDIA" },
      { id: 9, name: "SEAM ENGINEERS / NASH ROBOTICS, NASHIK INDIA" },
      { id: 10, name: "SHORE AUTO RUBBER EXPORTS PVT. LTD." },
      { id: 7, name: "SUNDARAM CLAYTON LTD., CHENNAI, INDIA" },
    ],
  },
  2: {
    id: 2,
    name: "Non Automotive",
    customers: [],
  },
};

export const STATIC_CATEGORIES = [
  { id: "cat-1", name: "AUTOMOTIVE PRODUCTS", slug: "automotive-products" },
  { id: "cat-2", name: "LOW PRESSURE HOSES", slug: "low-pressure-hoses" },
  { id: "cat-3", name: "INDUSTRIAL & CRITICAL RUBBER", slug: "industrial-critical-rubber" },
  { id: "cat-4", name: "AIR FILTER & TURBO CHARGER", slug: "air-filter-turbo-charger" },
  { id: "cat-5", name: "EXTRUDED RUBBER PROFILES", slug: "extruded-rubber-profiles" },
  { id: "cat-6", name: "SPECIAL DAMPER MOUNTINGS", slug: "special-damper-mountings" },
  { id: "cat-7", name: "COMPOUNDS", slug: "compounds" },
];

export const STATIC_PRODUCTS = [
  // AUTOMOTIVE PRODUCTS
  {
    id: "auto-1",
    category_name: "AUTOMOTIVE PRODUCTS",
    category_slug: "automotive-products",
    specification: "SPEC: ASTM D2000 M3BA610",
    customer: "EPDM",
    name: "STEERING COLUMN RUBBER GROMMETS / BELLOWS",
    description: "MAT // EPDM / SBR",
    image_url: "/images/product_card_1.png",
  },
  {
    id: "auto-2",
    category_name: "AUTOMOTIVE PRODUCTS",
    category_slug: "automotive-products",
    specification: "SPEC: SAE J200 3CH715",
    customer: "NBR",
    name: "RUBBER REBOUND SLIDER",
    description: "MAT // NBR / WEAR RESISTANT",
    image_url: "/images/product_card_2.png",
  },
  {
    id: "auto-3",
    category_name: "AUTOMOTIVE PRODUCTS",
    category_slug: "automotive-products",
    specification: "SPEC: ASTM D2000 M2AA508",
    customer: "Natural Rubber (NR)",
    name: "AUTOMOTIVE RUBBER MOUNTINGS FOR AIR PRESSURE TANK SEAT",
    description: "MAT // NATURAL RUBBER",
    image_url: "/images/product_card_3.png",
  },
  {
    id: "auto-4",
    category_name: "AUTOMOTIVE PRODUCTS",
    category_slug: "automotive-products",
    specification: "SPEC: ASTM D2000 M4CH614",
    customer: "Epichlorohydrin (ECO)",
    name: "DIESEL FILTER RUBBER AIR DUCT AIR CLEANER PIPES & ELBOWS",
    description: "MAT // EPICHLOROHYDRIN",
    image_url: "/images/product_card_4.png",
  },
  {
    id: "auto-5",
    category_name: "AUTOMOTIVE PRODUCTS",
    category_slug: "automotive-products",
    specification: "SPEC: ASTM D2000 M2BC510",
    customer: "Neoprene (CR)",
    name: "PROTECTIVE SLEEVES, DUST BOOTS, BELLOWS & WEATHER PROTECTIVE COVERS",
    description: "MAT // NEOPRENE (CR)",
    image_url: "/images/product_card_5.png",
  },
  {
    id: "auto-6",
    category_name: "AUTOMOTIVE PRODUCTS",
    category_slug: "automotive-products",
    specification: "SPEC: SAE J200 2AA815",
    customer: "Heavy Duty NR Compound",
    name: "RUBBER PAD FOR LEAF SPRING SEAT ENDS",
    description: "MAT // HEAVY DUTY NR",
    image_url: "/images/product_card_1.png",
  },
  {
    id: "auto-7",
    category_name: "AUTOMOTIVE PRODUCTS",
    category_slug: "automotive-products",
    specification: "SPEC: ASTM D2000 MULTI-SPEC",
    customer: "EPDM",
    name: "DIFFERENT TYPES OF RUBBER MOUNTINGS",
    description: "MAT // EPDM / NR BLEND",
    image_url: "/images/product_card_2.png",
  },
  {
    id: "auto-8",
    category_name: "AUTOMOTIVE PRODUCTS",
    category_slug: "automotive-products",
    specification: "SPEC: ASTM D2000 M1BG610",
    customer: "NBR with Fabric Insert",
    name: "RUBBER DIAPHRAGMS",
    description: "MAT // NBR / FABRIC REINFORCED",
    image_url: "/images/product_card_3.png",
  },
  {
    id: "auto-9",
    category_name: "AUTOMOTIVE PRODUCTS",
    category_slug: "automotive-products",
    specification: "SPEC: ASTM D2000 M5GE408",
    customer: "LVI-Soft Silicon (VMQ)",
    name: "RUBBER DAMPER ASSEMBLY FOR TACHOMETER MOUNTINGS",
    description: "MAT // SILICON RUBBER",
    image_url: "/images/product_card_4.png",
  },
  {
    id: "auto-10",
    category_name: "AUTOMOTIVE PRODUCTS",
    category_slug: "automotive-products",
    specification: "SPEC: SAE J200 3BA714",
    customer: "Weather Resistant EPDM",
    name: "RUBBER STRAPS & STRIPS FOR AIR FILTER MOUNTINGS WITH S.S. HOOKS",
    description: "MAT // WEATHER RESISTANT",
    image_url: "/images/product_card_5.png",
  },
  {
    id: "auto-11",
    category_name: "AUTOMOTIVE PRODUCTS",
    category_slug: "automotive-products",
    specification: "SPEC: SAE J200 CLASS EE/EG",
    customer: "Silicon",
    name: "REINFORCED SILICON RUBBER SLEEVES / ELBOWS FOR TURBO CHARGER HOSES",
    description: "MAT // ARAMID / POLYESTER REINFORCEMENT",
    image_url: "/images/product_card_1.png",
  },
  {
    id: "auto-12",
    category_name: "AUTOMOTIVE PRODUCTS",
    category_slug: "automotive-products",
    specification: "SPEC: OEM DYNAMIC GRADE SPEC",
    customer: "Premium NR",
    name: "ENGINE MOUNTING PARTS FOR EXPORT CARS",
    description: "MAT // PREMIUM NR",
    image_url: "/images/product_card_2.png",
  },
  {
    id: "auto-13",
    category_name: "AUTOMOTIVE PRODUCTS",
    category_slug: "automotive-products",
    specification: "SPEC: ASTM D2000 AA SPEC",
    customer: "SBR",
    name: "RUBBER MOUNTINGS & BUMPERS FOR EXPORT CARS",
    description: "MAT // SBR / NR BLEND",
    image_url: "/images/product_card_3.png",
  },
  {
    id: "auto-14",
    category_name: "AUTOMOTIVE PRODUCTS",
    category_slug: "automotive-products",
    specification: "SPEC: SAE J903",
    customer: "Epichlorohydrin Natural Blend",
    name: "RUBBER WIPER BLADES",
    description: "MAT // EPICHLOROHYDRIN",
    image_url: "/images/product_card_4.png",
  },
  {
    id: "auto-15",
    category_name: "AUTOMOTIVE PRODUCTS",
    category_slug: "automotive-products",
    specification: "SPEC: SAE J200 5DA712",
    customer: "Triple Composite EPDM",
    name: "RUBBER/PLASTIC & ALUMINIUM CO-EXTRUDED PROFILES FOR AUTOMOTIVE",
    description: "MAT // TRIPLE COMPOSITE",
    image_url: "/images/product_card_5.png",
  },
  {
    id: "auto-16",
    category_name: "AUTOMOTIVE PRODUCTS",
    category_slug: "automotive-products",
    specification: "SPEC: ASTM D2000 M2HK810",
    customer: "Fluorocarbon (FKM / Viton)",
    name: "RUBBER SEALS FOR RADIAL PISTON ACTUATORS & SOLENOID VALVES",
    description: "MAT // FLUOROCARBON",
    image_url: "/images/product_card_1.png",
  },
  {
    id: "auto-17",
    category_name: "AUTOMOTIVE PRODUCTS",
    category_slug: "automotive-products",
    specification: "SPEC: UL94-V0 FIRE RETARDANT",
    customer: "Flame Retardant Neoprene (CR)",
    name: "RUBBER SLEEVES FOR CABLES AND WIRING HARNESSES",
    description: "MAT // FLAME RETARDANT",
    image_url: "/images/product_card_2.png",
  },
  {
    id: "auto-18",
    category_name: "AUTOMOTIVE PRODUCTS",
    category_slug: "automotive-products",
    specification: "SPEC: ASTM D2000 BG GRADE",
    customer: "High Heat Heavy Duty Fabric",
    name: "RUBBER DIAPHRAGMS FOR ACTUATORS",
    description: "MAT // HEAT RESISTANT",
    image_url: "/images/product_card_3.png",
  },
  {
    id: "auto-19",
    category_name: "AUTOMOTIVE PRODUCTS",
    category_slug: "automotive-products",
    specification: "SPEC: ASTM D2000 STANDARDS",
    customer: "Custom Calendered Raw Compound",
    name: "RUBBER COMPOUND FOR AUTOMOTIVE RUBBER HOSE",
    description: "MAT // CUSTOM COMPOUND",
    image_url: "/images/product_card_4.png",
  },

  // LOW PRESSURE HOSES
  {
    id: "hose-1",
    category_name: "LOW PRESSURE HOSES",
    category_slug: "low-pressure-hoses",
    specification: "SPEC: SAE J30 R7",
    customer: "NBR / CR DUAL EXTRUSION",
    name: "LOW PRESSURE FUEL & OIL DELIVERY RUBBER HOSE",
    description: "MAT // NBR CORE / CR OUTER",
    image_url: "/images/product_card_5.png",
  },
  {
    id: "hose-2",
    category_name: "LOW PRESSURE HOSES",
    category_slug: "low-pressure-hoses",
    specification: "SPEC: DIN 73379",
    customer: "EPDM",
    name: "RADIATOR & COOLANT BENT RUBBER HOSE FOR DIESEL ENGINES",
    description: "MAT // EPDM WITH POLYESTER",
    image_url: "/images/product_card_1.png",
  },
  {
    id: "hose-3",
    category_name: "LOW PRESSURE HOSES",
    category_slug: "low-pressure-hoses",
    specification: "SPEC: ISO 4079",
    customer: "SBR / EPDM BLENDS",
    name: "TEXTILE REINFORCED WATER DISCHARGE FLUID HOSE",
    description: "MAT // SBR BRAID REINFORCED",
    image_url: "/images/product_card_2.png",
  },

  // INDUSTRIAL & CRITICAL RUBBER
  {
    id: "ind-1",
    category_name: "INDUSTRIAL & CRITICAL RUBBER",
    category_slug: "industrial-critical-rubber",
    specification: "SPEC: ASTM D2000 M3GE710",
    customer: "SILICONE (VMQ)",
    name: "HIGH TEMPERATURE SILICONE GASKETS FOR INDUSTRIAL OVENS",
    description: "MAT // HIGH TEMPERATURE VMQ",
    image_url: "/images/product_card_3.png",
  },
  {
    id: "ind-2",
    category_name: "INDUSTRIAL & CRITICAL RUBBER",
    category_slug: "industrial-critical-rubber",
    specification: "SPEC: SAE J200 2BG715",
    customer: "NBR / BR COMPOSITE",
    name: "HEAVY DUTY ANTI-VIBRATION INDUSTRIAL MOUNTINGS",
    description: "MAT // NITRILE / METAL INSERT",
    image_url: "/images/product_card_4.png",
  },
  {
    id: "ind-3",
    category_name: "INDUSTRIAL & CRITICAL RUBBER",
    category_slug: "industrial-critical-rubber",
    specification: "SPEC: ASTM D2000 M1AA810",
    customer: "NATURAL RUBBER (NR)",
    name: "CRITICAL RUBBER TO METAL BONDED SUSPENSION PADS",
    description: "MAT // NR TO STEEL SHELL",
    image_url: "/images/product_card_5.png",
  },

  // AIR FILTER & TURBO CHARGER
  {
    id: "turbo-1",
    category_name: "AIR FILTER & TURBO CHARGER",
    category_slug: "air-filter-turbo-charger",
    specification: "SPEC: SAE J200 CLASS EE",
    customer: "SILICONE / ARAMID (KEVLAR)",
    name: "TURBOCHARGER CONVOLUTED HOSE FOR HIGH PRESSURE DUCTS",
    description: "MAT // ARAMID BRAID SILICONE",
    image_url: "/images/product_card_1.png",
  },
  {
    id: "turbo-2",
    category_name: "AIR FILTER & TURBO CHARGER",
    category_slug: "air-filter-turbo-charger",
    specification: "SPEC: ASTM D2000 M2BC614",
    customer: "CHLOROPRENE (CR)",
    name: "FLEXIBLE AIR CLEANER INTAKE BELLOWS",
    description: "MAT // HEAVY DUTY CR",
    image_url: "/images/product_card_2.png",
  },

  // EXTRUDED RUBBER PROFILES
  {
    id: "prof-1",
    category_name: "EXTRUDED RUBBER PROFILES",
    category_slug: "extruded-rubber-profiles",
    specification: "SPEC: ASTM D2000 M3BA712",
    customer: "EPICHLOROHYDRIN / SPONGE",
    name: "AUTOMOTIVE DOOR AND BOOT WEATHERSTRIP EXTRUSIONS",
    description: "MAT // DUAL DENSITY EPDM",
    image_url: "/images/product_card_3.png",
  },
  {
    id: "prof-2",
    category_name: "EXTRUDED RUBBER PROFILES",
    category_slug: "extruded-rubber-profiles",
    specification: "SPEC: SAE J200 3CH810",
    customer: "NBR EXTRUDED",
    name: "OIL RESISTANT EXTRUDED SQUARE CHANNEL PROFILE",
    description: "MAT // HIGH ACCYLONITRILE",
    image_url: "/images/product_card_4.png",
  },

  // SPECIAL DAMPER MOUNTINGS
  {
    id: "damp-1",
    category_name: "SPECIAL DAMPER MOUNTINGS",
    category_slug: "special-damper-mountings",
    specification: "SPEC: OEM DYNAMIC GRADE",
    customer: "NATURAL RUBBER (NR)",
    name: "TUNED TORSIONAL VIBRATION DAMPER FOR ENGINE CRANKSHAFTS",
    description: "MAT // SHEAR DAMPING NR",
    image_url: "/images/product_card_5.png",
  },
  {
    id: "damp-2",
    category_name: "SPECIAL DAMPER MOUNTINGS",
    category_slug: "special-damper-mountings",
    specification: "SPEC: ASTM D2000 M2BC710",
    customer: "NEOPRENE (CR)",
    name: "SPECIALIZED SHOCK ABSORBING MOUNTS FOR INDUSTRIAL UNITS",
    description: "MAT // CR / STEEL INSERTS",
    image_url: "/images/product_card_1.png",
  },
];

export const STATIC_COMPOUNDS = [
  {
    id: "comp-1",
    specification: "SPEC: ASTM D2000 M3BA610",
    customer: "EPDM",
    name: "STEERING COLUMN RUBBER GROMMETS / BELLOWS",
    description: "MAT // EPDM / SBR",
    image_url: "/images/product_card_1.png",
  },
  {
    id: "comp-2",
    specification: "SPEC: SAE J200 3CH715",
    customer: "NBR",
    name: "RUBBER REBOUND SLIDER",
    description: "MAT // NBR / WEAR RESI...",
    image_url: "/images/product_card_2.png",
  },
  {
    id: "comp-3",
    specification: "SPEC: ASTM D2000 M2AA508",
    customer: "NATURAL RUBBER (NR)",
    name: "AUTOMOTIVE RUBBER MOUNTINGS FOR AIR PRESSURE TANK SEAT...",
    description: "MAT // NATURAL RUBBER ...",
    image_url: "/images/product_card_3.png",
  },
  {
    id: "comp-4",
    specification: "SPEC: ASTM D2000 M4CH614",
    customer: "EPICHLOROHYDRIN (ECO)",
    name: "DIESEL FILTER RUBBER AIR DUCT AIR CLEANER PIPES & ELBOWS",
    description: "MAT // EPICHLOROHYDRIN...",
    image_url: "/images/product_card_4.png",
  },
  {
    id: "comp-5",
    specification: "SPEC: ASTM D2000 M2BC510",
    customer: "NEOPRENE (CR)",
    name: "PROTECTIVE SLEEVES, DUST BOOTS, BELLOWS & WEATHER PROTECTIVE...",
    description: "MAT // NEOPRENE (CR)",
    image_url: "/images/product_card_5.png",
  },
  {
    id: "comp-6",
    specification: "SPEC: SAE J200 2AA815",
    customer: "HEAVY-DUTY NR COMPOUND",
    name: "RUBBER PAD FOR LEAF SPRING SEAT ENDS",
    description: "MAT // HEAVY-DUTY NR C...",
    image_url: "/images/product_card_1.png",
  },
  {
    id: "comp-7",
    specification: "SPEC: ASTM D2000 MULTI-SPEC",
    customer: "EPDM",
    name: "DIFFERENT TYPES OF RUBBER MOUNTINGS",
    description: "MAT // EPDM / NBR CUST...",
    image_url: "/images/product_card_2.png",
  },
  {
    id: "comp-8",
    specification: "SPEC: ASTM D2000 M1BG610",
    customer: "NBR WITH FABRIC INLAY (NYLON",
    name: "RUBBER DIAPHRAGMS",
    description: "MAT // NBR WITH FABRIC...",
    image_url: "/images/product_card_3.png",
  },
  {
    id: "comp-9",
    specification: "SPEC: ASTM D2000 M5GE408",
    customer: "ULTRA-SOFT SILICONE (VMQ)",
    name: "RUBBER DAMPER ASSEMBLY FOR TACHOMETER MOUNTINGS",
    description: "MAT // ULTRA-SOFT SILI...",
    image_url: "/images/product_card_4.png",
  },
  {
    id: "comp-10",
    specification: "SPEC: SAE J200 3BA714",
    customer: "WEATHER RESISTANT EPDM",
    name: "RUBBER STRAPS & STRIPS FOR AIR FILTER MOUNTINGS WITH S.S. HOOKS",
    description: "MAT // WEATHER RESISTA...",
    image_url: "/images/product_card_5.png",
  },
  {
    id: "comp-11",
    specification: "SPEC: SAE J200 CLASS EE/EG",
    customer: "KEVLAR",
    name: "REINFORCED SILICON RUBBER SLEEVES / ELBOWS FOR TURBO CHARGER...",
    description: "MAT // KEVLAR/POLYESTE...",
    image_url: "/images/product_card_1.png",
  },
  {
    id: "comp-12",
    specification: "SPEC: OEM DYNAMIC GRADE SPEC",
    customer: "PREMIUM NR",
    name: "ENGINE MOUNTING PARTS FOR EXPORT CARS",
    description: "MAT // PREMIUM NR / CA...",
    image_url: "/images/product_card_2.png",
  },
  {
    id: "comp-13",
    specification: "SPEC: ASTM D2000 AA SPEC",
    customer: "SBR",
    name: "RUBBER MOUNTINGS & BUMPERS FOR EXPORT CARS",
    description: "MAT // SBR / NBR BLEND",
    image_url: "/images/product_card_3.png",
  },
  {
    id: "comp-14",
    specification: "SPEC: SAE J903",
    customer: "CHLORINATED NATURAL RUBBER",
    name: "RUBBER WIPER BLADES",
    description: "MAT // CHLORINATED NAT...",
    image_url: "/images/product_card_4.png",
  },
  {
    id: "comp-15",
    specification: "SPEC: SAE J200 5DA712",
    customer: "TRIPLE COMPOSITE: EPDM",
    name: "RUBBER/PLASTIC & ALUMINIUM CO-EXTRUDED PROFILES FOR AUTOMOTIVE",
    description: "MAT // TRIPLE COMPOSIT...",
    image_url: "/images/product_card_5.png",
  },
  {
    id: "comp-16",
    specification: "SPEC: ASTM D2000 M2HK810",
    customer: "FLUOROCARBON (FKM - VITON)",
    name: "RUBBER SEALS FOR RADIAL PISTON ACTUATORS & SOLENOID VALVES",
    description: "MAT // FLUOROCARBON (F...",
    image_url: "/images/product_card_1.png",
  },
  {
    id: "comp-17",
    specification: "SPEC: UL94-V0 FIRE RETARDANT",
    customer: "FLAME RETARDANT NEOPRENE (CR)",
    name: "RUBBER SLEEVES FOR CABLES AND WIRING HARNESSES",
    description: "MAT // FLAME RETARDANT...",
    image_url: "/images/product_card_2.png",
  },
  {
    id: "comp-18",
    specification: "SPEC: ASTM D2000 BG GRADE",
    customer: "NBR WITH HEAVY DUTY FABRIC CORE",
    name: "RUBBER DIAPHRAGMS FOR ACTUATORS",
    description: "MAT // NBR WITH HEAVY ...",
    image_url: "/images/product_card_3.png",
  },
  {
    id: "comp-19",
    specification: "SPEC: ASTM D2000 STANDARDS",
    customer: "CUSTOM CALENDERED RAW COMPOUNDS (EPDM",
    name: "RUBBER COMPOUND FOR AUTOMOTIVE RUBBER HOSE",
    description: "MAT // CUSTOM CALENDER...",
    image_url: "/images/product_card_4.png",
  },
];

export const STATIC_MACHINERY = [
  {
    id: "mach-1",
    subtitle: "MACHINERY // HIGH SPEC MOULDING",
    name: "INJECTION MOULDING MACHINES",
    specs: [
      "Thermoplastic flow control systems",
      "Capacity range from 75T to 350T",
      "Dedicated mold accuracy tooling",
      "High-speed production capabilities",
      "Suitable for precision technical rubber mouldings"
    ],
    image_url: "/images/machineryCard1.png",
    make: "Demag",
    year_of_purchase: 2018,
    tonnage_or_capacity: "75T - 350T",
    total_machines: 4,
  },
  {
    id: "mach-2",
    subtitle: "MACHINERY // VACUUM VULCANIZATION",
    name: "VACUUM COMPRESSION MOULDING MACHINES",
    specs: [
      "Dual station shuttle systems",
      "PLC microprocessor control board",
      "Capacity range from 150T to 250T",
      "Fully enclosed vacuum chamber enclosures",
      "Intended for high density, defect-free seals"
    ],
    image_url: "/images/machineryCard2.png",
    make: "Tung Yu",
    year_of_purchase: 2019,
    tonnage_or_capacity: "150T - 250T",
    total_machines: 3,
  },
  {
    id: "mach-3",
    subtitle: "MACHINERY // HIGH TONNAGE MOULDING",
    name: "COMPRESSION MOULDING MACHINES",
    specs: [
      "Multi-station daylight press configurations",
      "Press tonnage from 50T to 250T",
      "Max platen size up to 600 x 600 mm",
      "Integrated microprocessor temperature controller",
      "Heavy-duty architecture built for continuous runs"
    ],
    image_url: "/images/machineryCard3.png",
    make: "Local Brand",
    year_of_purchase: 2015,
    tonnage_or_capacity: "50T - 250T",
    total_machines: 8,
  },
  {
    id: "mach-4",
    subtitle: "MACHINERY // COMPOUND PREPARATION",
    name: "KNEADER (HYDRAULIC) FOR COLORED COMPOUND MIXING",
    specs: [
      "Vessel capacities of 35L, 55L, and 75L",
      "Environmentally sealed dust-free batch systems",
      "Heavy-duty stainless steel water cooled jackets",
      "Strictly segregated black & colored compound stations",
      "Automatic real-time temperature monitoring"
    ],
    image_url: "/images/machineryCard4.png",
    make: "Moriyama",
    year_of_purchase: 2020,
    tonnage_or_capacity: "35L - 75L",
    total_machines: 2,
  },
  {
    id: "mach-5",
    subtitle: "MACHINERY // MATERIAL PROCESSING",
    name: "MIXING MILL FOR COLORED COMPOUNDS",
    specs: [
      "Dual-roll open cold feed mixing mills",
      "Roll sizes: 12x30, 14x36, and 16x42 inches",
      "High capacity water cooling circulation",
      "Integrated batch off systems with conveying reels",
      "Dedicated stations eliminating cross-contamination"
    ],
    image_url: "/images/machineryCard5.png",
    make: "Farrel",
    year_of_purchase: 2016,
    tonnage_or_capacity: "12 - 16 inch rolls",
    total_machines: 3,
  },
  {
    id: "mach-6",
    subtitle: "MACHINERY // CALENDERING & SHEETING",
    name: "3 ROLL CALENDER MACHINE FOR RUBBER SHEETING",
    specs: [
      "High precision micrometric roll gapping gague",
      "Maximum sheeting width up to 600 mm",
      "Integrated hot-water and steam heating systems",
      "Formulated for uniform rubber sheets",
      "Integrated co-frictioning for hose reinforcing fabrics"
    ],
    image_url: "/images/machineryCard6.png",
    make: "Comerio",
    year_of_purchase: 2017,
    tonnage_or_capacity: "Sheeting Width 600mm",
    total_machines: 1,
  },
  {
    id: "mach-7",
    subtitle: "MACHINERY // PROFILE EXTRUSION",
    name: "EXTRUDERS",
    specs: [
      "Coexisting cold feed and hot feed extruder heads",
      "Screw diameters: 50 mm, 60 mm, and 75 mm",
      "Automated multi-zone jacketed heating and cooling",
      "Designed for shaped strips, seals, and hose extrusions",
      "Variable frequency controllers for profile stability"
    ],
    image_url: "/images/machineryCard7.png",
    make: "Troester",
    year_of_purchase: 2021,
    tonnage_or_capacity: "Screw Dia 50-75mm",
    total_machines: 2,
  },
  {
    id: "mach-8",
    subtitle: "MACHINERY // DIRECT STEAM CURING",
    name: "STEAM VULCANIZERS",
    specs: [
      "Direct injected steam autoclaves for enclosed curing",
      "Vessel sizes: diameter up to 1000 mm, length 3000 mm",
      "Programmable stepping temperature schedules",
      "Safety secured automatic pressure lock mechanisms",
      "Reserved for large extruded hose reels & couplings"
    ],
    image_url: "/images/machineryCard8.png",
    make: "Autoclave India",
    year_of_purchase: 2014,
    tonnage_or_capacity: "Length 3000mm / Dia 1000mm",
    total_machines: 2,
  },
  {
    id: "mach-9",
    subtitle: "MACHINERY // UTILITY SYSTEMS",
    name: "STEAM BOILER",
    specs: [
      "Saturated steam capacity: 300 to 600 kg/hr",
      "Working steam pressures: 7 to 10.5 kg/cm2",
      "Compatible with solid fuels, diesel, and liquid gas",
      "Automatic electronic feed water regulators",
      "High safety pressure vent shunts and valves"
    ],
    image_url: "/images/machineryCard9.png",
    make: "Thermax",
    year_of_purchase: 2015,
    tonnage_or_capacity: "300 - 600 kg/hr",
    total_machines: 1,
  },
];

export const STATIC_CERTIFICATIONS = [
  {
    id: 2,
    name: "IATF 16949:2016",
    image: "https://bymer.pythonanywhere.com/media/certifications/IATF_16949-ENG-191027-2015-AQ-IND-IATF-3_J52.png",
  },
  {
    id: 1,
    name: "ISO 14001 : 2015",
    image: "https://bymer.pythonanywhere.com/media/certifications/ISO-14001-2015.png",
  },
  {
    id: 4,
    name: "ISO 45001 : 2018",
    image: "https://bymer.pythonanywhere.com/media/certifications/OHS_ISO_45001-2018_2026_J52.png",
  },
  {
    id: 3,
    name: "ISO 9001 : 2015",
    image: "https://bymer.pythonanywhere.com/media/certifications/ISO_9001_-_Ver_03_-_J42_-_2027_1.png",
  },
];
